### ISSUE TITLE
Question in ranking.py

### ISSUE THREAD

**Issue by Tingji2419** [Didayolo/ranky#4]
Hello! 
Thanks for your work and recently i (might) found a mistake in a line 214 in ranking.py while using your package. 

Should it be " ranking = rank(m,axis=axis) " instead "ranking = rank(m) "?  (Code below as the same way)

Thanks for your reply.

**Comment by Didayolo** [comment]
Hello,

Thank you for your message. Good catch!

I'll fix it and add some unit testing with different axis.

**Comment by Didayolo** [comment]
@Tingji2419 

Fixed!

https://github.com/Didayolo/ranky/commit/4e9c606b731da5a6463f2793c2554ca7c0d641ed
